<?php
/**
 * Plugin Name: EZZY Partner Routing
 * Description: Mobile-friendly partner category modal with editable platform/category routing for EZZY.
 * Version: 1.3.0
 * Author: EZZY
 * License: GPL-2.0-or-later
 */

if (!defined('ABSPATH')) exit;

define('EZZY_PR_VERSION', '1.3.0');
define('EZZY_PR_DIR', plugin_dir_path(__FILE__));
define('EZZY_PR_URL', plugin_dir_url(__FILE__));
define('EZZY_PR_REFERRAL_PARAM', 'ezzy_referral_code');
define('EZZY_PR_REFERRAL_OUT_PARAM', 'ref');
define('EZZY_PR_REFERRAL_COOKIE', 'ezzy_pr_referral');
define('EZZY_PR_REFERRAL_TTL', 30 * DAY_IN_SECONDS);

function ezzy_pr_activate() {
    if (!get_option('ezzy_pr_platforms')) {
        update_option('ezzy_pr_platforms', array(
            array('id'=>'well','name'=>'Well','url'=>'https://well.ezzy.ph','partner_url'=>'https://well.ezzy.ph/become-a-partner/','icon'=>'💇','active'=>1),
            array('id'=>'stay','name'=>'Stay','url'=>'https://stay.ezzy.ph','partner_url'=>'https://stay.ezzy.ph/become-a-partner/','icon'=>'🏨','active'=>1),
            array('id'=>'eat','name'=>'Eat','url'=>'https://eat.ezzy.ph','partner_url'=>'https://eat.ezzy.ph/become-a-partner/','icon'=>'🍽️','active'=>1),
        ));
    }
    if (!get_option('ezzy_pr_categories')) {
        update_option('ezzy_pr_categories', array(
            array('id'=>'salon','name'=>'Salon','icon'=>'💇','platform'=>'well','url'=>'https://well.ezzy.ph/become-a-partner/','active'=>1),
            array('id'=>'barber','name'=>'Barber','icon'=>'💈','platform'=>'well','url'=>'https://well.ezzy.ph/become-a-partner/','active'=>1),
            array('id'=>'nail-salon','name'=>'Nail Salon','icon'=>'💅','platform'=>'well','url'=>'https://well.ezzy.ph/become-a-partner/','active'=>1),
            array('id'=>'massage','name'=>'Massage','icon'=>'💆','platform'=>'well','url'=>'https://well.ezzy.ph/become-a-partner/','active'=>1),
            array('id'=>'hotel','name'=>'Hotel','icon'=>'🏨','platform'=>'stay','url'=>'https://stay.ezzy.ph/become-a-partner/','active'=>1),
            array('id'=>'restaurant','name'=>'Restaurant','icon'=>'🍽️','platform'=>'eat','url'=>'https://eat.ezzy.ph/become-a-partner/','active'=>1),
        ));
    }
    if (!get_option('ezzy_pr_settings')) {
        update_option('ezzy_pr_settings', array(
            'trigger_class'=>'ezzy-partner-trigger',
            'title'=>'Become an EZZY Partner',
            'subtitle'=>'What type of business or service do you offer?',
            'search_placeholder'=>'Search business type...',
            'fallback_text'=>"Can't find your business?",
            'fallback_url'=>'',
        ));
    }
}
register_activation_hook(__FILE__, 'ezzy_pr_activate');

function ezzy_pr_get($key, $default=array()) {
    $v=get_option($key, $default);
    return is_array($v) ? $v : $default;
}


function ezzy_pr_allow_svg_upload($mimes) {
    if (current_user_can('manage_options')) {
        $mimes['svg'] = 'image/svg+xml';
    }
    return $mimes;
}
add_filter('upload_mimes', 'ezzy_pr_allow_svg_upload');

function ezzy_pr_admin_menu() {
    add_menu_page('Partner Routing','EZZY Partner Routing','manage_options','ezzy-partner-routing','ezzy_pr_dashboard','dashicons-randomize',58);
    add_submenu_page('ezzy-partner-routing','Platforms','Platforms','manage_options','ezzy-pr-platforms','ezzy_pr_platforms');
    add_submenu_page('ezzy-partner-routing','Categories','Categories','manage_options','ezzy-pr-categories','ezzy_pr_categories');
    add_submenu_page('ezzy-partner-routing','Settings','Settings','manage_options','ezzy-pr-settings','ezzy_pr_settings');
}
add_action('admin_menu','ezzy_pr_admin_menu');

function ezzy_pr_plugin_action_links($links) {
    $settings_url = admin_url('admin.php?page=ezzy-pr-settings');
    $settings_link = '<a href="' . esc_url($settings_url) . '">' . esc_html__('Settings', 'ezzy-partner-routing') . '</a>';
    array_unshift($links, $settings_link);
    return $links;
}
add_filter('plugin_action_links_' . plugin_basename(__FILE__), 'ezzy_pr_plugin_action_links');


function ezzy_pr_admin_assets($hook) {
    if (strpos($hook,'ezzy-pr')===false && $hook!=='toplevel_page_ezzy-partner-routing') return;
    wp_enqueue_style('ezzy-pr-fontawesome', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css', array(), '6.7.2');
    wp_enqueue_style('ezzy-pr-admin', EZZY_PR_URL.'assets/admin.css', array('ezzy-pr-fontawesome'), EZZY_PR_VERSION);
    wp_enqueue_media();
    wp_enqueue_script('ezzy-pr-admin', EZZY_PR_URL.'assets/admin.js', array('jquery'), EZZY_PR_VERSION, true);
}
add_action('admin_enqueue_scripts','ezzy_pr_admin_assets');

function ezzy_pr_dashboard() {
    $p=ezzy_pr_get('ezzy_pr_platforms'); $c=ezzy_pr_get('ezzy_pr_categories');
    echo '<div class="wrap ezzy-pr-admin"><h1>EZZY Partner Routing</h1><p>Manage EZZY platforms and the business categories that route partners to them.</p>';
    echo '<div class="ezzy-pr-stats"><div><strong>'.count(array_filter($p,fn($x)=>!empty($x['active']))).'</strong><span>Active Platforms</span></div><div><strong>'.count(array_filter($c,fn($x)=>!empty($x['active']))).'</strong><span>Active Categories</span></div></div>';
    echo '<p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=ezzy-pr-categories')).'">Manage Categories</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=ezzy-pr-platforms')).'">Manage Platforms</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=ezzy-pr-settings')).'">Settings</a></p>';
    echo '<h2>How it works</h2><ol><li>Add an EZZY platform and its partner URL.</li><li>Add business categories and assign each one to a platform.</li><li>Set the exact destination URL for each category.</li><li>Add the CSS class <code>ezzy-partner-trigger</code> to your existing Elementor button.</li></ol></div>';
}


function ezzy_pr_icon_catalog() {
    return array(
        'fa-solid fa-ad'=>'Ad',
        'fa-solid fa-address-book'=>'Address Book',
        'fa-solid fa-address-card'=>'Address Card',
        'fa-solid fa-adjust'=>'Adjust',
        'fa-solid fa-air-freshener'=>'Air Freshener',
        'fa-solid fa-align-center'=>'Align Center',
        'fa-solid fa-align-justify'=>'Align Justify',
        'fa-solid fa-align-left'=>'Align Left',
        'fa-solid fa-align-right'=>'Align Right',
        'fa-solid fa-allergies'=>'Allergies',
        'fa-solid fa-ambulance'=>'Ambulance',
        'fa-solid fa-american-sign-language-interpreting'=>'American Sign Language Interpreting',
        'fa-solid fa-anchor'=>'Anchor',
        'fa-solid fa-angle-double-down'=>'Angle Double Down',
        'fa-solid fa-angle-double-left'=>'Angle Double Left',
        'fa-solid fa-angle-double-right'=>'Angle Double Right',
        'fa-solid fa-angle-double-up'=>'Angle Double Up',
        'fa-solid fa-angle-down'=>'Angle Down',
        'fa-solid fa-angle-left'=>'Angle Left',
        'fa-solid fa-angle-right'=>'Angle Right',
        'fa-solid fa-angle-up'=>'Angle Up',
        'fa-solid fa-angry'=>'Angry',
        'fa-solid fa-ankh'=>'Ankh',
        'fa-solid fa-archive'=>'Archive',
        'fa-solid fa-archway'=>'Archway',
        'fa-solid fa-arrow-alt-circle-down'=>'Arrow Alt Circle Down',
        'fa-solid fa-arrow-alt-circle-left'=>'Arrow Alt Circle Left',
        'fa-solid fa-arrow-alt-circle-right'=>'Arrow Alt Circle Right',
        'fa-solid fa-arrow-alt-circle-up'=>'Arrow Alt Circle Up',
        'fa-solid fa-arrow-circle-down'=>'Arrow Circle Down',
        'fa-solid fa-arrow-circle-left'=>'Arrow Circle Left',
        'fa-solid fa-arrow-circle-right'=>'Arrow Circle Right',
        'fa-solid fa-arrow-circle-up'=>'Arrow Circle Up',
        'fa-solid fa-arrow-down'=>'Arrow Down',
        'fa-solid fa-arrow-left'=>'Arrow Left',
        'fa-solid fa-arrow-right'=>'Arrow Right',
        'fa-solid fa-arrow-up'=>'Arrow Up',
        'fa-solid fa-arrows-alt-h'=>'Arrows Alt H',
        'fa-solid fa-arrows-alt-v'=>'Arrows Alt V',
        'fa-solid fa-assistive-listening-systems'=>'Assistive Listening Systems',
        'fa-solid fa-asterisk'=>'Asterisk',
        'fa-solid fa-at'=>'At',
        'fa-solid fa-atlas'=>'Atlas',
        'fa-solid fa-atom'=>'Atom',
        'fa-solid fa-audio-description'=>'Audio Description',
        'fa-solid fa-award'=>'Award',
        'fa-solid fa-baby'=>'Baby',
        'fa-solid fa-baby-carriage'=>'Baby Carriage',
        'fa-solid fa-backspace'=>'Backspace',
        'fa-solid fa-backward'=>'Backward',
        'fa-solid fa-bacon'=>'Bacon',
        'fa-solid fa-bacteria'=>'Bacteria',
        'fa-solid fa-bacterium'=>'Bacterium',
        'fa-solid fa-bag-shopping'=>'Bag Shopping',
        'fa-solid fa-bahai'=>'Bahai',
        'fa-solid fa-balance-scale'=>'Balance Scale',
        'fa-solid fa-balance-scale-left'=>'Balance Scale Left',
        'fa-solid fa-balance-scale-right'=>'Balance Scale Right',
        'fa-solid fa-ban'=>'Ban',
        'fa-solid fa-band-aid'=>'Band Aid',
        'fa-solid fa-barcode'=>'Barcode',
        'fa-solid fa-bars'=>'Bars',
        'fa-solid fa-baseball'=>'Baseball',
        'fa-solid fa-baseball-ball'=>'Baseball Ball',
        'fa-solid fa-basketball'=>'Basketball',
        'fa-solid fa-basketball-ball'=>'Basketball Ball',
        'fa-solid fa-bath'=>'Bath',
        'fa-solid fa-battery-empty'=>'Battery Empty',
        'fa-solid fa-battery-full'=>'Battery Full',
        'fa-solid fa-battery-half'=>'Battery Half',
        'fa-solid fa-battery-quarter'=>'Battery Quarter',
        'fa-solid fa-battery-three-quarters'=>'Battery Three Quarters',
        'fa-solid fa-bed'=>'Bed',
        'fa-solid fa-beer'=>'Beer',
        'fa-solid fa-bell'=>'Bell',
        'fa-solid fa-bell-slash'=>'Bell Slash',
        'fa-solid fa-bezier-curve'=>'Bezier Curve',
        'fa-solid fa-bible'=>'Bible',
        'fa-solid fa-bicycle'=>'Bicycle',
        'fa-solid fa-biking'=>'Biking',
        'fa-solid fa-binoculars'=>'Binoculars',
        'fa-solid fa-biohazard'=>'Biohazard',
        'fa-solid fa-birthday-cake'=>'Birthday Cake',
        'fa-solid fa-blender'=>'Blender',
        'fa-solid fa-blender-phone'=>'Blender Phone',
        'fa-solid fa-blind'=>'Blind',
        'fa-solid fa-blog'=>'Blog',
        'fa-solid fa-bold'=>'Bold',
        'fa-solid fa-bolt'=>'Bolt',
        'fa-solid fa-bomb'=>'Bomb',
        'fa-solid fa-bone'=>'Bone',
        'fa-solid fa-bong'=>'Bong',
        'fa-solid fa-book'=>'Book',
        'fa-solid fa-book-dead'=>'Book Dead',
        'fa-solid fa-book-medical'=>'Book Medical',
        'fa-solid fa-book-open'=>'Book Open',
        'fa-solid fa-book-reader'=>'Book Reader',
        'fa-solid fa-bookmark'=>'Bookmark',
        'fa-solid fa-border-all'=>'Border All',
        'fa-solid fa-border-none'=>'Border None',
        'fa-solid fa-border-style'=>'Border Style',
        'fa-solid fa-bowl-food'=>'Bowl Food',
        'fa-solid fa-bowling-ball'=>'Bowling Ball',
        'fa-solid fa-box'=>'Box',
        'fa-solid fa-box-open'=>'Box Open',
        'fa-solid fa-box-tissue'=>'Box Tissue',
        'fa-solid fa-boxes'=>'Boxes',
        'fa-solid fa-braille'=>'Braille',
        'fa-solid fa-brain'=>'Brain',
        'fa-solid fa-bread-slice'=>'Bread Slice',
        'fa-solid fa-briefcase'=>'Briefcase',
        'fa-solid fa-briefcase-medical'=>'Briefcase Medical',
        'fa-solid fa-broadcast-tower'=>'Broadcast Tower',
        'fa-solid fa-broom'=>'Broom',
        'fa-solid fa-brush'=>'Brush',
        'fa-solid fa-bug'=>'Bug',
        'fa-solid fa-building'=>'Building',
        'fa-solid fa-building-columns'=>'Building Columns',
        'fa-solid fa-bullhorn'=>'Bullhorn',
        'fa-solid fa-bullseye'=>'Bullseye',
        'fa-solid fa-burger'=>'Burger',
        'fa-solid fa-burn'=>'Burn',
        'fa-solid fa-bus'=>'Bus',
        'fa-solid fa-business-time'=>'Business Time',
        'fa-solid fa-cake-candles'=>'Cake Candles',
        'fa-solid fa-calculator'=>'Calculator',
        'fa-solid fa-calendar'=>'Calendar',
        'fa-solid fa-calendar-check'=>'Calendar Check',
        'fa-solid fa-calendar-day'=>'Calendar Day',
        'fa-solid fa-calendar-days'=>'Calendar Days',
        'fa-solid fa-calendar-minus'=>'Calendar Minus',
        'fa-solid fa-calendar-plus'=>'Calendar Plus',
        'fa-solid fa-calendar-times'=>'Calendar Times',
        'fa-solid fa-calendar-week'=>'Calendar Week',
        'fa-solid fa-camera'=>'Camera',
        'fa-solid fa-camera-retro'=>'Camera Retro',
        'fa-solid fa-campground'=>'Campground',
        'fa-solid fa-candy-cane'=>'Candy Cane',
        'fa-solid fa-cannabis'=>'Cannabis',
        'fa-solid fa-capsules'=>'Capsules',
        'fa-solid fa-car'=>'Car',
        'fa-solid fa-car-battery'=>'Car Battery',
        'fa-solid fa-car-crash'=>'Car Crash',
        'fa-solid fa-car-rear'=>'Car Rear',
        'fa-solid fa-car-side'=>'Car Side',
        'fa-solid fa-caravan'=>'Caravan',
        'fa-solid fa-caret-down'=>'Caret Down',
        'fa-solid fa-caret-left'=>'Caret Left',
        'fa-solid fa-caret-right'=>'Caret Right',
        'fa-solid fa-caret-square-down'=>'Caret Square Down',
        'fa-solid fa-caret-square-left'=>'Caret Square Left',
        'fa-solid fa-caret-square-right'=>'Caret Square Right',
        'fa-solid fa-caret-square-up'=>'Caret Square Up',
        'fa-solid fa-caret-up'=>'Caret Up',
        'fa-solid fa-carrot'=>'Carrot',
        'fa-solid fa-cart-arrow-down'=>'Cart Arrow Down',
        'fa-solid fa-cart-plus'=>'Cart Plus',
        'fa-solid fa-cart-shopping'=>'Cart Shopping',
        'fa-solid fa-cash-register'=>'Cash Register',
        'fa-solid fa-cat'=>'Cat',
        'fa-solid fa-certificate'=>'Certificate',
        'fa-solid fa-chair'=>'Chair',
        'fa-solid fa-chalkboard'=>'Chalkboard',
        'fa-solid fa-chalkboard-teacher'=>'Chalkboard Teacher',
        'fa-solid fa-chalkboard-user'=>'Chalkboard User',
        'fa-solid fa-champagne-glasses'=>'Champagne Glasses',
        'fa-solid fa-charging-station'=>'Charging Station',
        'fa-solid fa-chart-area'=>'Chart Area',
        'fa-solid fa-chart-bar'=>'Chart Bar',
        'fa-solid fa-chart-line'=>'Chart Line',
        'fa-solid fa-chart-pie'=>'Chart Pie',
        'fa-solid fa-check'=>'Check',
        'fa-solid fa-check-circle'=>'Check Circle',
        'fa-solid fa-check-double'=>'Check Double',
        'fa-solid fa-check-square'=>'Check Square',
        'fa-solid fa-cheese'=>'Cheese',
        'fa-solid fa-chess'=>'Chess',
        'fa-solid fa-chess-bishop'=>'Chess Bishop',
        'fa-solid fa-chess-board'=>'Chess Board',
        'fa-solid fa-chess-king'=>'Chess King',
        'fa-solid fa-chess-knight'=>'Chess Knight',
        'fa-solid fa-chess-pawn'=>'Chess Pawn',
        'fa-solid fa-chess-queen'=>'Chess Queen',
        'fa-solid fa-chess-rook'=>'Chess Rook',
        'fa-solid fa-chevron-circle-down'=>'Chevron Circle Down',
        'fa-solid fa-chevron-circle-left'=>'Chevron Circle Left',
        'fa-solid fa-chevron-circle-right'=>'Chevron Circle Right',
        'fa-solid fa-chevron-circle-up'=>'Chevron Circle Up',
        'fa-solid fa-chevron-down'=>'Chevron Down',
        'fa-solid fa-chevron-left'=>'Chevron Left',
        'fa-solid fa-chevron-right'=>'Chevron Right',
        'fa-solid fa-chevron-up'=>'Chevron Up',
        'fa-solid fa-child'=>'Child',
        'fa-solid fa-church'=>'Church',
        'fa-solid fa-circle'=>'Circle',
        'fa-solid fa-circle-check'=>'Circle Check',
        'fa-solid fa-circle-exclamation'=>'Circle Exclamation',
        'fa-solid fa-circle-info'=>'Circle Info',
        'fa-solid fa-circle-notch'=>'Circle Notch',
        'fa-solid fa-circle-xmark'=>'Circle Xmark',
        'fa-solid fa-city'=>'City',
        'fa-solid fa-clinic-medical'=>'Clinic Medical',
        'fa-solid fa-clipboard'=>'Clipboard',
        'fa-solid fa-clipboard-check'=>'Clipboard Check',
        'fa-solid fa-clipboard-list'=>'Clipboard List',
        'fa-solid fa-clock'=>'Clock',
        'fa-solid fa-clone'=>'Clone',
        'fa-solid fa-closed-captioning'=>'Closed Captioning',
        'fa-solid fa-cloud'=>'Cloud',
        'fa-solid fa-cloud-meatball'=>'Cloud Meatball',
        'fa-solid fa-cloud-moon'=>'Cloud Moon',
        'fa-solid fa-cloud-moon-rain'=>'Cloud Moon Rain',
        'fa-solid fa-cloud-rain'=>'Cloud Rain',
        'fa-solid fa-cloud-showers-heavy'=>'Cloud Showers Heavy',
        'fa-solid fa-cloud-sun'=>'Cloud Sun',
        'fa-solid fa-cloud-sun-rain'=>'Cloud Sun Rain',
        'fa-solid fa-cocktail'=>'Cocktail',
        'fa-solid fa-code'=>'Code',
        'fa-solid fa-code-branch'=>'Code Branch',
        'fa-solid fa-coffee'=>'Coffee',
        'fa-solid fa-cog'=>'Cog',
        'fa-solid fa-cogs'=>'Cogs',
        'fa-solid fa-coins'=>'Coins',
        'fa-solid fa-columns'=>'Columns',
        'fa-solid fa-comment'=>'Comment',
        'fa-solid fa-comment-dollar'=>'Comment Dollar',
        'fa-solid fa-comment-dots'=>'Comment Dots',
        'fa-solid fa-comment-medical'=>'Comment Medical',
        'fa-solid fa-comment-slash'=>'Comment Slash',
        'fa-solid fa-comments'=>'Comments',
        'fa-solid fa-comments-dollar'=>'Comments Dollar',
        'fa-solid fa-compact-disc'=>'Compact Disc',
        'fa-solid fa-compass'=>'Compass',
        'fa-solid fa-compress'=>'Compress',
        'fa-solid fa-concierge-bell'=>'Concierge Bell',
        'fa-solid fa-cookie'=>'Cookie',
        'fa-solid fa-cookie-bite'=>'Cookie Bite',
        'fa-solid fa-copy'=>'Copy',
        'fa-solid fa-copyright'=>'Copyright',
        'fa-solid fa-couch'=>'Couch',
        'fa-solid fa-credit-card'=>'Credit Card',
        'fa-solid fa-crop'=>'Crop',
        'fa-solid fa-cross'=>'Cross',
        'fa-solid fa-crosshairs'=>'Crosshairs',
        'fa-solid fa-crow'=>'Crow',
        'fa-solid fa-crown'=>'Crown',
        'fa-solid fa-crutch'=>'Crutch',
        'fa-solid fa-cube'=>'Cube',
        'fa-solid fa-cubes'=>'Cubes',
        'fa-solid fa-cut'=>'Cut',
        'fa-solid fa-database'=>'Database',
        'fa-solid fa-deaf'=>'Deaf',
        'fa-solid fa-democrat'=>'Democrat',
        'fa-solid fa-desktop'=>'Desktop',
        'fa-solid fa-dharmachakra'=>'Dharmachakra',
        'fa-solid fa-diagnoses'=>'Diagnoses',
        'fa-solid fa-dice'=>'Dice',
        'fa-solid fa-dice-five'=>'Dice Five',
        'fa-solid fa-dice-four'=>'Dice Four',
        'fa-solid fa-dice-one'=>'Dice One',
        'fa-solid fa-dice-six'=>'Dice Six',
        'fa-solid fa-dice-three'=>'Dice Three',
        'fa-solid fa-dice-two'=>'Dice Two',
        'fa-solid fa-digital-tachograph'=>'Digital Tachograph',
        'fa-solid fa-directions'=>'Directions',
        'fa-solid fa-disease'=>'Disease',
        'fa-solid fa-divide'=>'Divide',
        'fa-solid fa-dizzy'=>'Dizzy',
        'fa-solid fa-dna'=>'Dna',
        'fa-solid fa-dog'=>'Dog',
        'fa-solid fa-dollar-sign'=>'Dollar Sign',
        'fa-solid fa-dolly'=>'Dolly',
        'fa-solid fa-dolly-flatbed'=>'Dolly Flatbed',
        'fa-solid fa-donate'=>'Donate',
        'fa-solid fa-door-closed'=>'Door Closed',
        'fa-solid fa-door-open'=>'Door Open',
        'fa-solid fa-dot-circle'=>'Dot Circle',
        'fa-solid fa-dove'=>'Dove',
        'fa-solid fa-download'=>'Download',
        'fa-solid fa-drafting-compass'=>'Drafting Compass',
        'fa-solid fa-dragon'=>'Dragon',
        'fa-solid fa-draw-polygon'=>'Draw Polygon',
        'fa-solid fa-droplet'=>'Droplet',
        'fa-solid fa-drum'=>'Drum',
        'fa-solid fa-drum-steelpan'=>'Drum Steelpan',
        'fa-solid fa-drumstick-bite'=>'Drumstick Bite',
        'fa-solid fa-dumbbell'=>'Dumbbell',
        'fa-solid fa-dumpster'=>'Dumpster',
        'fa-solid fa-dumpster-fire'=>'Dumpster Fire',
        'fa-solid fa-dungeon'=>'Dungeon',
        'fa-solid fa-edit'=>'Edit',
        'fa-solid fa-egg'=>'Egg',
        'fa-solid fa-eject'=>'Eject',
        'fa-solid fa-ellipsis-h'=>'Ellipsis H',
        'fa-solid fa-ellipsis-v'=>'Ellipsis V',
        'fa-solid fa-envelope'=>'Envelope',
        'fa-solid fa-envelope-open'=>'Envelope Open',
        'fa-solid fa-envelope-open-text'=>'Envelope Open Text',
        'fa-solid fa-envelope-square'=>'Envelope Square',
        'fa-solid fa-equals'=>'Equals',
        'fa-solid fa-eraser'=>'Eraser',
        'fa-solid fa-ethernet'=>'Ethernet',
        'fa-solid fa-euro-sign'=>'Euro Sign',
        'fa-solid fa-exclamation'=>'Exclamation',
        'fa-solid fa-exclamation-circle'=>'Exclamation Circle',
        'fa-solid fa-exclamation-triangle'=>'Exclamation Triangle',
        'fa-solid fa-expand'=>'Expand',
        'fa-solid fa-eye'=>'Eye',
        'fa-solid fa-eye-dropper'=>'Eye Dropper',
        'fa-solid fa-eye-slash'=>'Eye Slash',
        'fa-solid fa-fan'=>'Fan',
        'fa-solid fa-fast-backward'=>'Fast Backward',
        'fa-solid fa-fast-forward'=>'Fast Forward',
        'fa-solid fa-faucet'=>'Faucet',
        'fa-solid fa-faucet-drip'=>'Faucet Drip',
        'fa-solid fa-fax'=>'Fax',
        'fa-solid fa-feather'=>'Feather',
        'fa-solid fa-female'=>'Female',
        'fa-solid fa-fighter-jet'=>'Fighter Jet',
        'fa-solid fa-file'=>'File',
        'fa-solid fa-file-archive'=>'File Archive',
        'fa-solid fa-file-audio'=>'File Audio',
        'fa-solid fa-file-code'=>'File Code',
        'fa-solid fa-file-contract'=>'File Contract',
        'fa-solid fa-file-csv'=>'File Csv',
        'fa-solid fa-file-download'=>'File Download',
        'fa-solid fa-file-excel'=>'File Excel',
        'fa-solid fa-file-export'=>'File Export',
        'fa-solid fa-file-image'=>'File Image',
        'fa-solid fa-file-import'=>'File Import',
        'fa-solid fa-file-invoice'=>'File Invoice',
        'fa-solid fa-file-invoice-dollar'=>'File Invoice Dollar',
        'fa-solid fa-file-lines'=>'File Lines',
        'fa-solid fa-file-medical'=>'File Medical',
        'fa-solid fa-file-pdf'=>'File Pdf',
        'fa-solid fa-file-powerpoint'=>'File Powerpoint',
        'fa-solid fa-file-prescription'=>'File Prescription',
        'fa-solid fa-file-signature'=>'File Signature',
        'fa-solid fa-file-upload'=>'File Upload',
        'fa-solid fa-file-video'=>'File Video',
        'fa-solid fa-file-word'=>'File Word',
        'fa-solid fa-fill'=>'Fill',
        'fa-solid fa-fill-drip'=>'Fill Drip',
        'fa-solid fa-film'=>'Film',
        'fa-solid fa-filter'=>'Filter',
        'fa-solid fa-fingerprint'=>'Fingerprint',
        'fa-solid fa-fire'=>'Fire',
        'fa-solid fa-fire-extinguisher'=>'Fire Extinguisher',
        'fa-solid fa-first-aid'=>'First Aid',
        'fa-solid fa-fish'=>'Fish',
        'fa-solid fa-fist-raised'=>'Fist Raised',
        'fa-solid fa-flag'=>'Flag',
        'fa-solid fa-flag-checkered'=>'Flag Checkered',
        'fa-solid fa-flag-usa'=>'Flag Usa',
        'fa-solid fa-flask'=>'Flask',
        'fa-solid fa-flushed'=>'Flushed',
        'fa-solid fa-folder'=>'Folder',
        'fa-solid fa-folder-minus'=>'Folder Minus',
        'fa-solid fa-folder-open'=>'Folder Open',
        'fa-solid fa-folder-plus'=>'Folder Plus',
        'fa-solid fa-font'=>'Font',
        'fa-solid fa-football'=>'Football',
        'fa-solid fa-football-ball'=>'Football Ball',
        'fa-solid fa-forward'=>'Forward',
        'fa-solid fa-frog'=>'Frog',
        'fa-solid fa-frown'=>'Frown',
        'fa-solid fa-frown-open'=>'Frown Open',
        'fa-solid fa-funnel-dollar'=>'Funnel Dollar',
        'fa-solid fa-futbol'=>'Futbol',
        'fa-solid fa-gamepad'=>'Gamepad',
        'fa-solid fa-gas-pump'=>'Gas Pump',
        'fa-solid fa-gavel'=>'Gavel',
        'fa-solid fa-gear'=>'Gear',
        'fa-solid fa-gem'=>'Gem',
        'fa-solid fa-genderless'=>'Genderless',
        'fa-solid fa-ghost'=>'Ghost',
        'fa-solid fa-gift'=>'Gift',
        'fa-solid fa-gifts'=>'Gifts',
        'fa-solid fa-glass-cheers'=>'Glass Cheers',
        'fa-solid fa-glass-martini'=>'Glass Martini',
        'fa-solid fa-glass-whiskey'=>'Glass Whiskey',
        'fa-solid fa-glasses'=>'Glasses',
        'fa-solid fa-globe'=>'Globe',
        'fa-solid fa-globe-africa'=>'Globe Africa',
        'fa-solid fa-globe-americas'=>'Globe Americas',
        'fa-solid fa-globe-asia'=>'Globe Asia',
        'fa-solid fa-globe-europe'=>'Globe Europe',
        'fa-solid fa-golf-ball'=>'Golf Ball',
        'fa-solid fa-golf-ball-tee'=>'Golf Ball Tee',
        'fa-solid fa-gopuram'=>'Gopuram',
        'fa-solid fa-graduation-cap'=>'Graduation Cap',
        'fa-solid fa-greater-than'=>'Greater Than',
        'fa-solid fa-greater-than-equal'=>'Greater Than Equal',
        'fa-solid fa-grimace'=>'Grimace',
        'fa-solid fa-grin'=>'Grin',
        'fa-solid fa-grin-beam'=>'Grin Beam',
        'fa-solid fa-grin-beam-sweat'=>'Grin Beam Sweat',
        'fa-solid fa-grin-hearts'=>'Grin Hearts',
        'fa-solid fa-grin-squint'=>'Grin Squint',
        'fa-solid fa-grin-squint-tears'=>'Grin Squint Tears',
        'fa-solid fa-grin-stars'=>'Grin Stars',
        'fa-solid fa-grin-tears'=>'Grin Tears',
        'fa-solid fa-grin-tongue'=>'Grin Tongue',
        'fa-solid fa-grin-tongue-squint'=>'Grin Tongue Squint',
        'fa-solid fa-grin-tongue-wink'=>'Grin Tongue Wink',
        'fa-solid fa-grin-wink'=>'Grin Wink',
        'fa-solid fa-grip-horizontal'=>'Grip Horizontal',
        'fa-solid fa-grip-lines'=>'Grip Lines',
        'fa-solid fa-grip-lines-vertical'=>'Grip Lines Vertical',
        'fa-solid fa-grip-vertical'=>'Grip Vertical',
        'fa-solid fa-guitar'=>'Guitar',
        'fa-solid fa-h-square'=>'H Square',
        'fa-solid fa-hamburger'=>'Hamburger',
        'fa-solid fa-hammer'=>'Hammer',
        'fa-solid fa-hamsa'=>'Hamsa',
        'fa-solid fa-hand-holding'=>'Hand Holding',
        'fa-solid fa-hand-holding-heart'=>'Hand Holding Heart',
        'fa-solid fa-hand-holding-medical'=>'Hand Holding Medical',
        'fa-solid fa-hand-holding-usd'=>'Hand Holding Usd',
        'fa-solid fa-hand-holding-water'=>'Hand Holding Water',
        'fa-solid fa-hand-lizard'=>'Hand Lizard',
        'fa-solid fa-hand-middle-finger'=>'Hand Middle Finger',
        'fa-solid fa-hand-paper'=>'Hand Paper',
        'fa-solid fa-hand-peace'=>'Hand Peace',
        'fa-solid fa-hand-point-down'=>'Hand Point Down',
        'fa-solid fa-hand-point-left'=>'Hand Point Left',
        'fa-solid fa-hand-point-right'=>'Hand Point Right',
        'fa-solid fa-hand-point-up'=>'Hand Point Up',
        'fa-solid fa-hand-pointer'=>'Hand Pointer',
        'fa-solid fa-hand-rock'=>'Hand Rock',
        'fa-solid fa-hand-scissors'=>'Hand Scissors',
        'fa-solid fa-hand-sparkles'=>'Hand Sparkles',
        'fa-solid fa-hand-spock'=>'Hand Spock',
        'fa-solid fa-hands'=>'Hands',
        'fa-solid fa-hands-helping'=>'Hands Helping',
        'fa-solid fa-hands-wash'=>'Hands Wash',
        'fa-solid fa-handshake'=>'Handshake',
        'fa-solid fa-handshake-alt-slash'=>'Handshake Alt Slash',
        'fa-solid fa-handshake-slash'=>'Handshake Slash',
        'fa-solid fa-hanukiah'=>'Hanukiah',
        'fa-solid fa-hard-hat'=>'Hard Hat',
        'fa-solid fa-hashtag'=>'Hashtag',
        'fa-solid fa-hat-cowboy'=>'Hat Cowboy',
        'fa-solid fa-hat-cowboy-side'=>'Hat Cowboy Side',
        'fa-solid fa-hat-wizard'=>'Hat Wizard',
        'fa-solid fa-hdd'=>'Hdd',
        'fa-solid fa-head-side-cough'=>'Head Side Cough',
        'fa-solid fa-head-side-cough-slash'=>'Head Side Cough Slash',
        'fa-solid fa-head-side-mask'=>'Head Side Mask',
        'fa-solid fa-head-side-virus'=>'Head Side Virus',
        'fa-solid fa-heading'=>'Heading',
        'fa-solid fa-headphones'=>'Headphones',
        'fa-solid fa-headset'=>'Headset',
        'fa-solid fa-heart'=>'Heart',
        'fa-solid fa-heart-broken'=>'Heart Broken',
        'fa-solid fa-heart-pulse'=>'Heart Pulse',
        'fa-solid fa-heartbeat'=>'Heartbeat',
        'fa-solid fa-helicopter'=>'Helicopter',
        'fa-solid fa-highlighter'=>'Highlighter',
        'fa-solid fa-hiking'=>'Hiking',
        'fa-solid fa-hippo'=>'Hippo',
        'fa-solid fa-history'=>'History',
        'fa-solid fa-hockey-puck'=>'Hockey Puck',
        'fa-solid fa-holly-berry'=>'Holly Berry',
        'fa-solid fa-home'=>'Home',
        'fa-solid fa-horse'=>'Horse',
        'fa-solid fa-horse-head'=>'Horse Head',
        'fa-solid fa-hospital'=>'Hospital',
        'fa-solid fa-hospital-symbol'=>'Hospital Symbol',
        'fa-solid fa-hospital-user'=>'Hospital User',
        'fa-solid fa-hot-tub'=>'Hot Tub',
        'fa-solid fa-hotdog'=>'Hotdog',
        'fa-solid fa-hotel'=>'Hotel',
        'fa-solid fa-hourglass'=>'Hourglass',
        'fa-solid fa-hourglass-end'=>'Hourglass End',
        'fa-solid fa-hourglass-half'=>'Hourglass Half',
        'fa-solid fa-hourglass-start'=>'Hourglass Start',
        'fa-solid fa-house-chimney'=>'House Chimney',
        'fa-solid fa-house-chimney-user'=>'House Chimney User',
        'fa-solid fa-house-damage'=>'House Damage',
        'fa-solid fa-house-user'=>'House User',
        'fa-solid fa-hryvnia'=>'Hryvnia',
        'fa-solid fa-i-cursor'=>'I Cursor',
        'fa-solid fa-ice-cream'=>'Ice Cream',
        'fa-solid fa-icicles'=>'Icicles',
        'fa-solid fa-icons'=>'Icons',
        'fa-solid fa-id-badge'=>'Id Badge',
        'fa-solid fa-id-card'=>'Id Card',
        'fa-solid fa-igloo'=>'Igloo',
        'fa-solid fa-image'=>'Image',
        'fa-solid fa-images'=>'Images',
        'fa-solid fa-inbox'=>'Inbox',
        'fa-solid fa-indent'=>'Indent',
        'fa-solid fa-industry'=>'Industry',
        'fa-solid fa-infinity'=>'Infinity',
        'fa-solid fa-info'=>'Info',
        'fa-solid fa-info-circle'=>'Info Circle',
        'fa-solid fa-italic'=>'Italic',
        'fa-solid fa-jedi'=>'Jedi',
        'fa-solid fa-joint'=>'Joint',
        'fa-solid fa-journal-whills'=>'Journal Whills',
        'fa-solid fa-kaaba'=>'Kaaba',
        'fa-solid fa-key'=>'Key',
        'fa-solid fa-keyboard'=>'Keyboard',
        'fa-solid fa-khanda'=>'Khanda',
        'fa-solid fa-kiss'=>'Kiss',
        'fa-solid fa-kiss-beam'=>'Kiss Beam',
        'fa-solid fa-kiss-wink-heart'=>'Kiss Wink Heart',
        'fa-solid fa-kiwi-bird'=>'Kiwi Bird',
        'fa-solid fa-landmark'=>'Landmark',
        'fa-solid fa-language'=>'Language',
        'fa-solid fa-laptop'=>'Laptop',
        'fa-solid fa-laptop-code'=>'Laptop Code',
        'fa-solid fa-laptop-house'=>'Laptop House',
        'fa-solid fa-laptop-medical'=>'Laptop Medical',
        'fa-solid fa-laugh'=>'Laugh',
        'fa-solid fa-laugh-beam'=>'Laugh Beam',
        'fa-solid fa-laugh-squint'=>'Laugh Squint',
        'fa-solid fa-laugh-wink'=>'Laugh Wink',
        'fa-solid fa-layer-group'=>'Layer Group',
        'fa-solid fa-leaf'=>'Leaf',
        'fa-solid fa-lemon'=>'Lemon',
        'fa-solid fa-less-than'=>'Less Than',
        'fa-solid fa-less-than-equal'=>'Less Than Equal',
        'fa-solid fa-life-ring'=>'Life Ring',
        'fa-solid fa-lightbulb'=>'Lightbulb',
        'fa-solid fa-link'=>'Link',
        'fa-solid fa-lira-sign'=>'Lira Sign',
        'fa-solid fa-list'=>'List',
        'fa-solid fa-list-check'=>'List Check',
        'fa-solid fa-list-ol'=>'List Ol',
        'fa-solid fa-list-ul'=>'List Ul',
        'fa-solid fa-location-arrow'=>'Location Arrow',
        'fa-solid fa-location-dot'=>'Location Dot',
        'fa-solid fa-lock'=>'Lock',
        'fa-solid fa-lock-open'=>'Lock Open',
        'fa-solid fa-long-arrow-alt-down'=>'Long Arrow Alt Down',
        'fa-solid fa-long-arrow-alt-left'=>'Long Arrow Alt Left',
        'fa-solid fa-long-arrow-alt-right'=>'Long Arrow Alt Right',
        'fa-solid fa-long-arrow-alt-up'=>'Long Arrow Alt Up',
        'fa-solid fa-low-vision'=>'Low Vision',
        'fa-solid fa-luggage-cart'=>'Luggage Cart',
        'fa-solid fa-lungs'=>'Lungs',
        'fa-solid fa-lungs-virus'=>'Lungs Virus',
        'fa-solid fa-magic'=>'Magic',
        'fa-solid fa-magnet'=>'Magnet',
        'fa-solid fa-magnifying-glass'=>'Magnifying Glass',
        'fa-solid fa-mail-bulk'=>'Mail Bulk',
        'fa-solid fa-male'=>'Male',
        'fa-solid fa-map'=>'Map',
        'fa-solid fa-map-location-dot'=>'Map Location Dot',
        'fa-solid fa-map-marked'=>'Map Marked',
        'fa-solid fa-map-marker'=>'Map Marker',
        'fa-solid fa-map-pin'=>'Map Pin',
        'fa-solid fa-map-signs'=>'Map Signs',
        'fa-solid fa-marker'=>'Marker',
        'fa-solid fa-mars'=>'Mars',
        'fa-solid fa-mars-double'=>'Mars Double',
        'fa-solid fa-mars-stroke'=>'Mars Stroke',
        'fa-solid fa-mars-stroke-h'=>'Mars Stroke H',
        'fa-solid fa-mars-stroke-v'=>'Mars Stroke V',
        'fa-solid fa-mask'=>'Mask',
        'fa-solid fa-medal'=>'Medal',
        'fa-solid fa-medkit'=>'Medkit',
        'fa-solid fa-meh'=>'Meh',
        'fa-solid fa-meh-blank'=>'Meh Blank',
        'fa-solid fa-meh-rolling-eyes'=>'Meh Rolling Eyes',
        'fa-solid fa-memory'=>'Memory',
        'fa-solid fa-menorah'=>'Menorah',
        'fa-solid fa-mercury'=>'Mercury',
        'fa-solid fa-message'=>'Message',
        'fa-solid fa-meteor'=>'Meteor',
        'fa-solid fa-microchip'=>'Microchip',
        'fa-solid fa-microphone'=>'Microphone',
        'fa-solid fa-microphone-alt-slash'=>'Microphone Alt Slash',
        'fa-solid fa-microphone-slash'=>'Microphone Slash',
        'fa-solid fa-microscope'=>'Microscope',
        'fa-solid fa-minus'=>'Minus',
        'fa-solid fa-minus-circle'=>'Minus Circle',
        'fa-solid fa-minus-square'=>'Minus Square',
        'fa-solid fa-mitten'=>'Mitten',
        'fa-solid fa-mobile'=>'Mobile',
        'fa-solid fa-mobile-screen-button'=>'Mobile Screen Button',
        'fa-solid fa-money-bill'=>'Money Bill',
        'fa-solid fa-money-bill-wave'=>'Money Bill Wave',
        'fa-solid fa-money-check'=>'Money Check',
        'fa-solid fa-monument'=>'Monument',
        'fa-solid fa-moon'=>'Moon',
        'fa-solid fa-mortar-pestle'=>'Mortar Pestle',
        'fa-solid fa-mosque'=>'Mosque',
        'fa-solid fa-motorcycle'=>'Motorcycle',
        'fa-solid fa-mountain'=>'Mountain',
        'fa-solid fa-mountain-sun'=>'Mountain Sun',
        'fa-solid fa-mouse'=>'Mouse',
        'fa-solid fa-mouse-pointer'=>'Mouse Pointer',
        'fa-solid fa-mug-hot'=>'Mug Hot',
        'fa-solid fa-music'=>'Music',
        'fa-solid fa-network-wired'=>'Network Wired',
        'fa-solid fa-neuter'=>'Neuter',
        'fa-solid fa-newspaper'=>'Newspaper',
        'fa-solid fa-not-equal'=>'Not Equal',
        'fa-solid fa-notes-medical'=>'Notes Medical',
        'fa-solid fa-object-group'=>'Object Group',
        'fa-solid fa-object-ungroup'=>'Object Ungroup',
        'fa-solid fa-oil-can'=>'Oil Can',
        'fa-solid fa-om'=>'Om',
        'fa-solid fa-otter'=>'Otter',
        'fa-solid fa-outdent'=>'Outdent',
        'fa-solid fa-pager'=>'Pager',
        'fa-solid fa-paint-brush'=>'Paint Brush',
        'fa-solid fa-paint-roller'=>'Paint Roller',
        'fa-solid fa-palette'=>'Palette',
        'fa-solid fa-pallet'=>'Pallet',
        'fa-solid fa-paper-plane'=>'Paper Plane',
        'fa-solid fa-paperclip'=>'Paperclip',
        'fa-solid fa-parachute-box'=>'Parachute Box',
        'fa-solid fa-paragraph'=>'Paragraph',
        'fa-solid fa-parking'=>'Parking',
        'fa-solid fa-passport'=>'Passport',
        'fa-solid fa-pastafarianism'=>'Pastafarianism',
        'fa-solid fa-paste'=>'Paste',
        'fa-solid fa-pause'=>'Pause',
        'fa-solid fa-pause-circle'=>'Pause Circle',
        'fa-solid fa-paw'=>'Paw',
        'fa-solid fa-peace'=>'Peace',
        'fa-solid fa-pen'=>'Pen',
        'fa-solid fa-pen-fancy'=>'Pen Fancy',
        'fa-solid fa-pen-nib'=>'Pen Nib',
        'fa-solid fa-pen-square'=>'Pen Square',
        'fa-solid fa-pencil-ruler'=>'Pencil Ruler',
        'fa-solid fa-people-arrows'=>'People Arrows',
        'fa-solid fa-people-carry'=>'People Carry',
        'fa-solid fa-people-group'=>'People Group',
        'fa-solid fa-people-roof'=>'People Roof',
        'fa-solid fa-pepper-hot'=>'Pepper Hot',
        'fa-solid fa-percent'=>'Percent',
        'fa-solid fa-percentage'=>'Percentage',
        'fa-solid fa-person-biking'=>'Person Biking',
        'fa-solid fa-person-booth'=>'Person Booth',
        'fa-solid fa-person-chalkboard'=>'Person Chalkboard',
        'fa-solid fa-person-circle-question'=>'Person Circle Question',
        'fa-solid fa-person-running'=>'Person Running',
        'fa-solid fa-person-swimming'=>'Person Swimming',
        'fa-solid fa-person-walking'=>'Person Walking',
        'fa-solid fa-phone'=>'Phone',
        'fa-solid fa-phone-slash'=>'Phone Slash',
        'fa-solid fa-phone-square'=>'Phone Square',
        'fa-solid fa-phone-volume'=>'Phone Volume',
        'fa-solid fa-photo-video'=>'Photo Video',
        'fa-solid fa-piggy-bank'=>'Piggy Bank',
        'fa-solid fa-pills'=>'Pills',
        'fa-solid fa-pizza-slice'=>'Pizza Slice',
        'fa-solid fa-place-of-worship'=>'Place Of Worship',
        'fa-solid fa-plane'=>'Plane',
        'fa-solid fa-plane-arrival'=>'Plane Arrival',
        'fa-solid fa-plane-departure'=>'Plane Departure',
        'fa-solid fa-plane-slash'=>'Plane Slash',
        'fa-solid fa-play'=>'Play',
        'fa-solid fa-play-circle'=>'Play Circle',
        'fa-solid fa-plug'=>'Plug',
        'fa-solid fa-plus'=>'Plus',
        'fa-solid fa-plus-circle'=>'Plus Circle',
        'fa-solid fa-plus-square'=>'Plus Square',
        'fa-solid fa-podcast'=>'Podcast',
        'fa-solid fa-poll'=>'Poll',
        'fa-solid fa-poll-h'=>'Poll H',
        'fa-solid fa-poo'=>'Poo',
        'fa-solid fa-poo-storm'=>'Poo Storm',
        'fa-solid fa-poop'=>'Poop',
        'fa-solid fa-portrait'=>'Portrait',
        'fa-solid fa-pound-sign'=>'Pound Sign',
        'fa-solid fa-power-off'=>'Power Off',
        'fa-solid fa-pray'=>'Pray',
        'fa-solid fa-praying-hands'=>'Praying Hands',
        'fa-solid fa-prescription'=>'Prescription',
        'fa-solid fa-prescription-bottle'=>'Prescription Bottle',
        'fa-solid fa-print'=>'Print',
        'fa-solid fa-procedures'=>'Procedures',
        'fa-solid fa-project-diagram'=>'Project Diagram',
        'fa-solid fa-pump-medical'=>'Pump Medical',
        'fa-solid fa-pump-soap'=>'Pump Soap',
        'fa-solid fa-puzzle-piece'=>'Puzzle Piece',
        'fa-solid fa-qrcode'=>'Qrcode',
        'fa-solid fa-question'=>'Question',
        'fa-solid fa-question-circle'=>'Question Circle',
        'fa-solid fa-quidditch'=>'Quidditch',
        'fa-solid fa-quote-left'=>'Quote Left',
        'fa-solid fa-quote-right'=>'Quote Right',
        'fa-solid fa-quran'=>'Quran',
        'fa-solid fa-radiation'=>'Radiation',
        'fa-solid fa-rainbow'=>'Rainbow',
        'fa-solid fa-random'=>'Random',
        'fa-solid fa-receipt'=>'Receipt',
        'fa-solid fa-record-vinyl'=>'Record Vinyl',
        'fa-solid fa-recycle'=>'Recycle',
        'fa-solid fa-redo'=>'Redo',
        'fa-solid fa-registered'=>'Registered',
        'fa-solid fa-remove-format'=>'Remove Format',
        'fa-solid fa-reply'=>'Reply',
        'fa-solid fa-reply-all'=>'Reply All',
        'fa-solid fa-republican'=>'Republican',
        'fa-solid fa-restroom'=>'Restroom',
        'fa-solid fa-retweet'=>'Retweet',
        'fa-solid fa-ribbon'=>'Ribbon',
        'fa-solid fa-ring'=>'Ring',
        'fa-solid fa-road'=>'Road',
        'fa-solid fa-robot'=>'Robot',
        'fa-solid fa-rocket'=>'Rocket',
        'fa-solid fa-route'=>'Route',
        'fa-solid fa-rss'=>'Rss',
        'fa-solid fa-rss-square'=>'Rss Square',
        'fa-solid fa-ruble-sign'=>'Ruble Sign',
        'fa-solid fa-ruler'=>'Ruler',
        'fa-solid fa-ruler-combined'=>'Ruler Combined',
        'fa-solid fa-ruler-horizontal'=>'Ruler Horizontal',
        'fa-solid fa-ruler-vertical'=>'Ruler Vertical',
        'fa-solid fa-running'=>'Running',
        'fa-solid fa-rupee-sign'=>'Rupee Sign',
        'fa-solid fa-sad-cry'=>'Sad Cry',
        'fa-solid fa-sad-tear'=>'Sad Tear',
        'fa-solid fa-satellite'=>'Satellite',
        'fa-solid fa-satellite-dish'=>'Satellite Dish',
        'fa-solid fa-save'=>'Save',
        'fa-solid fa-scale-balanced'=>'Scale Balanced',
        'fa-solid fa-school'=>'School',
        'fa-solid fa-scissors'=>'Scissors',
        'fa-solid fa-screwdriver'=>'Screwdriver',
        'fa-solid fa-screwdriver-wrench'=>'Screwdriver Wrench',
        'fa-solid fa-scroll'=>'Scroll',
        'fa-solid fa-sd-card'=>'Sd Card',
        'fa-solid fa-search'=>'Search',
        'fa-solid fa-search-dollar'=>'Search Dollar',
        'fa-solid fa-search-location'=>'Search Location',
        'fa-solid fa-search-minus'=>'Search Minus',
        'fa-solid fa-search-plus'=>'Search Plus',
        'fa-solid fa-seedling'=>'Seedling',
        'fa-solid fa-server'=>'Server',
        'fa-solid fa-shapes'=>'Shapes',
        'fa-solid fa-share'=>'Share',
        'fa-solid fa-share-alt-square'=>'Share Alt Square',
        'fa-solid fa-share-square'=>'Share Square',
        'fa-solid fa-shekel-sign'=>'Shekel Sign',
        'fa-solid fa-shield-virus'=>'Shield Virus',
        'fa-solid fa-ship'=>'Ship',
        'fa-solid fa-shipping-fast'=>'Shipping Fast',
        'fa-solid fa-shoe-prints'=>'Shoe Prints',
        'fa-solid fa-shop'=>'Shop',
        'fa-solid fa-shop-slash'=>'Shop Slash',
        'fa-solid fa-shopping-bag'=>'Shopping Bag',
        'fa-solid fa-shopping-basket'=>'Shopping Basket',
        'fa-solid fa-shopping-cart'=>'Shopping Cart',
        'fa-solid fa-shower'=>'Shower',
        'fa-solid fa-shuttle-van'=>'Shuttle Van',
        'fa-solid fa-sign'=>'Sign',
        'fa-solid fa-sign-language'=>'Sign Language',
        'fa-solid fa-signature'=>'Signature',
        'fa-solid fa-sim-card'=>'Sim Card',
        'fa-solid fa-sink'=>'Sink',
        'fa-solid fa-sitemap'=>'Sitemap',
        'fa-solid fa-skating'=>'Skating',
        'fa-solid fa-skiing'=>'Skiing',
        'fa-solid fa-skiing-nordic'=>'Skiing Nordic',
        'fa-solid fa-skull'=>'Skull',
        'fa-solid fa-skull-crossbones'=>'Skull Crossbones',
        'fa-solid fa-slash'=>'Slash',
        'fa-solid fa-sleigh'=>'Sleigh',
        'fa-solid fa-sliders'=>'Sliders',
        'fa-solid fa-sliders-h'=>'Sliders H',
        'fa-solid fa-smile'=>'Smile',
        'fa-solid fa-smile-beam'=>'Smile Beam',
        'fa-solid fa-smile-wink'=>'Smile Wink',
        'fa-solid fa-smog'=>'Smog',
        'fa-solid fa-smoking'=>'Smoking',
        'fa-solid fa-smoking-ban'=>'Smoking Ban',
        'fa-solid fa-sms'=>'Sms',
        'fa-solid fa-snowboarding'=>'Snowboarding',
        'fa-solid fa-snowflake'=>'Snowflake',
        'fa-solid fa-snowman'=>'Snowman',
        'fa-solid fa-snowplow'=>'Snowplow',
        'fa-solid fa-soap'=>'Soap',
        'fa-solid fa-socks'=>'Socks',
        'fa-solid fa-solar-panel'=>'Solar Panel',
        'fa-solid fa-sort'=>'Sort',
        'fa-solid fa-sort-alpha-down'=>'Sort Alpha Down',
        'fa-solid fa-sort-alpha-up'=>'Sort Alpha Up',
        'fa-solid fa-sort-amount-down'=>'Sort Amount Down',
        'fa-solid fa-sort-amount-up'=>'Sort Amount Up',
        'fa-solid fa-sort-down'=>'Sort Down',
        'fa-solid fa-sort-numeric-down'=>'Sort Numeric Down',
        'fa-solid fa-sort-numeric-up'=>'Sort Numeric Up',
        'fa-solid fa-sort-up'=>'Sort Up',
        'fa-solid fa-spa'=>'Spa',
        'fa-solid fa-space-shuttle'=>'Space Shuttle',
        'fa-solid fa-spell-check'=>'Spell Check',
        'fa-solid fa-spider'=>'Spider',
        'fa-solid fa-spinner'=>'Spinner',
        'fa-solid fa-splotch'=>'Splotch',
        'fa-solid fa-spray-can'=>'Spray Can',
        'fa-solid fa-square'=>'Square',
        'fa-solid fa-square-full'=>'Square Full',
        'fa-solid fa-square-parking'=>'Square Parking',
        'fa-solid fa-stamp'=>'Stamp',
        'fa-solid fa-star'=>'Star',
        'fa-solid fa-star-and-crescent'=>'Star And Crescent',
        'fa-solid fa-star-half'=>'Star Half',
        'fa-solid fa-star-of-david'=>'Star Of David',
        'fa-solid fa-star-of-life'=>'Star Of Life',
        'fa-solid fa-step-backward'=>'Step Backward',
        'fa-solid fa-step-forward'=>'Step Forward',
        'fa-solid fa-stethoscope'=>'Stethoscope',
        'fa-solid fa-sticky-note'=>'Sticky Note',
        'fa-solid fa-stop'=>'Stop',
        'fa-solid fa-stop-circle'=>'Stop Circle',
        'fa-solid fa-store'=>'Store',
        'fa-solid fa-store-alt-slash'=>'Store Alt Slash',
        'fa-solid fa-store-slash'=>'Store Slash',
        'fa-solid fa-stream'=>'Stream',
        'fa-solid fa-street-view'=>'Street View',
        'fa-solid fa-strikethrough'=>'Strikethrough',
        'fa-solid fa-stroopwafel'=>'Stroopwafel',
        'fa-solid fa-subscript'=>'Subscript',
        'fa-solid fa-subway'=>'Subway',
        'fa-solid fa-suitcase'=>'Suitcase',
        'fa-solid fa-suitcase-rolling'=>'Suitcase Rolling',
        'fa-solid fa-sun'=>'Sun',
        'fa-solid fa-superscript'=>'Superscript',
        'fa-solid fa-surprise'=>'Surprise',
        'fa-solid fa-swatchbook'=>'Swatchbook',
        'fa-solid fa-swimmer'=>'Swimmer',
        'fa-solid fa-swimming-pool'=>'Swimming Pool',
        'fa-solid fa-synagogue'=>'Synagogue',
        'fa-solid fa-sync'=>'Sync',
        'fa-solid fa-syringe'=>'Syringe',
        'fa-solid fa-table'=>'Table',
        'fa-solid fa-table-tennis'=>'Table Tennis',
        'fa-solid fa-table-tennis-paddle-ball'=>'Table Tennis Paddle Ball',
        'fa-solid fa-tablet'=>'Tablet',
        'fa-solid fa-tablets'=>'Tablets',
        'fa-solid fa-tag'=>'Tag',
        'fa-solid fa-tags'=>'Tags',
        'fa-solid fa-tape'=>'Tape',
        'fa-solid fa-tasks'=>'Tasks',
        'fa-solid fa-taxi'=>'Taxi',
        'fa-solid fa-teeth'=>'Teeth',
        'fa-solid fa-teeth-open'=>'Teeth Open',
        'fa-solid fa-temperature-high'=>'Temperature High',
        'fa-solid fa-temperature-low'=>'Temperature Low',
        'fa-solid fa-tenge'=>'Tenge',
        'fa-solid fa-terminal'=>'Terminal',
        'fa-solid fa-text-height'=>'Text Height',
        'fa-solid fa-text-width'=>'Text Width',
        'fa-solid fa-th'=>'Th',
        'fa-solid fa-th-large'=>'Th Large',
        'fa-solid fa-th-list'=>'Th List',
        'fa-solid fa-theater-masks'=>'Theater Masks',
        'fa-solid fa-thermometer'=>'Thermometer',
        'fa-solid fa-thermometer-empty'=>'Thermometer Empty',
        'fa-solid fa-thermometer-full'=>'Thermometer Full',
        'fa-solid fa-thermometer-half'=>'Thermometer Half',
        'fa-solid fa-thermometer-quarter'=>'Thermometer Quarter',
        'fa-solid fa-thermometer-three-quarters'=>'Thermometer Three Quarters',
        'fa-solid fa-thumbs-down'=>'Thumbs Down',
        'fa-solid fa-thumbs-up'=>'Thumbs Up',
        'fa-solid fa-thumbtack'=>'Thumbtack',
        'fa-solid fa-ticket'=>'Ticket',
        'fa-solid fa-times'=>'Times',
        'fa-solid fa-times-circle'=>'Times Circle',
        'fa-solid fa-tint'=>'Tint',
        'fa-solid fa-tint-slash'=>'Tint Slash',
        'fa-solid fa-tired'=>'Tired',
        'fa-solid fa-toggle-off'=>'Toggle Off',
        'fa-solid fa-toggle-on'=>'Toggle On',
        'fa-solid fa-toilet'=>'Toilet',
        'fa-solid fa-toilet-paper'=>'Toilet Paper',
        'fa-solid fa-toilet-paper-slash'=>'Toilet Paper Slash',
        'fa-solid fa-toolbox'=>'Toolbox',
        'fa-solid fa-tools'=>'Tools',
        'fa-solid fa-tooth'=>'Tooth',
        'fa-solid fa-torah'=>'Torah',
        'fa-solid fa-torii-gate'=>'Torii Gate',
        'fa-solid fa-tractor'=>'Tractor',
        'fa-solid fa-trademark'=>'Trademark',
        'fa-solid fa-traffic-light'=>'Traffic Light',
        'fa-solid fa-trailer'=>'Trailer',
        'fa-solid fa-train'=>'Train',
        'fa-solid fa-tram'=>'Tram',
        'fa-solid fa-transgender'=>'Transgender',
        'fa-solid fa-trash'=>'Trash',
        'fa-solid fa-trash-restore'=>'Trash Restore',
        'fa-solid fa-tree'=>'Tree',
        'fa-solid fa-triangle-exclamation'=>'Triangle Exclamation',
        'fa-solid fa-trophy'=>'Trophy',
        'fa-solid fa-truck'=>'Truck',
        'fa-solid fa-truck-fast'=>'Truck Fast',
        'fa-solid fa-truck-loading'=>'Truck Loading',
        'fa-solid fa-truck-monster'=>'Truck Monster',
        'fa-solid fa-truck-moving'=>'Truck Moving',
        'fa-solid fa-truck-pickup'=>'Truck Pickup',
        'fa-solid fa-tshirt'=>'Tshirt',
        'fa-solid fa-tty'=>'Tty',
        'fa-solid fa-tv'=>'Tv',
        'fa-solid fa-umbrella'=>'Umbrella',
        'fa-solid fa-umbrella-beach'=>'Umbrella Beach',
        'fa-solid fa-underline'=>'Underline',
        'fa-solid fa-undo'=>'Undo',
        'fa-solid fa-universal-access'=>'Universal Access',
        'fa-solid fa-university'=>'University',
        'fa-solid fa-unlink'=>'Unlink',
        'fa-solid fa-unlock'=>'Unlock',
        'fa-solid fa-upload'=>'Upload',
        'fa-solid fa-user'=>'User',
        'fa-solid fa-user-alt-slash'=>'User Alt Slash',
        'fa-solid fa-user-astronaut'=>'User Astronaut',
        'fa-solid fa-user-check'=>'User Check',
        'fa-solid fa-user-circle'=>'User Circle',
        'fa-solid fa-user-clock'=>'User Clock',
        'fa-solid fa-user-cog'=>'User Cog',
        'fa-solid fa-user-doctor'=>'User Doctor',
        'fa-solid fa-user-edit'=>'User Edit',
        'fa-solid fa-user-friends'=>'User Friends',
        'fa-solid fa-user-graduate'=>'User Graduate',
        'fa-solid fa-user-injured'=>'User Injured',
        'fa-solid fa-user-lock'=>'User Lock',
        'fa-solid fa-user-md'=>'User Md',
        'fa-solid fa-user-minus'=>'User Minus',
        'fa-solid fa-user-ninja'=>'User Ninja',
        'fa-solid fa-user-nurse'=>'User Nurse',
        'fa-solid fa-user-plus'=>'User Plus',
        'fa-solid fa-user-secret'=>'User Secret',
        'fa-solid fa-user-shield'=>'User Shield',
        'fa-solid fa-user-slash'=>'User Slash',
        'fa-solid fa-user-tag'=>'User Tag',
        'fa-solid fa-user-tie'=>'User Tie',
        'fa-solid fa-user-times'=>'User Times',
        'fa-solid fa-users'=>'Users',
        'fa-solid fa-users-cog'=>'Users Cog',
        'fa-solid fa-users-slash'=>'Users Slash',
        'fa-solid fa-utensil-spoon'=>'Utensil Spoon',
        'fa-solid fa-utensils'=>'Utensils',
        'fa-solid fa-van-shuttle'=>'Van Shuttle',
        'fa-solid fa-vector-square'=>'Vector Square',
        'fa-solid fa-venus'=>'Venus',
        'fa-solid fa-venus-double'=>'Venus Double',
        'fa-solid fa-venus-mars'=>'Venus Mars',
        'fa-solid fa-vest'=>'Vest',
        'fa-solid fa-vest-patches'=>'Vest Patches',
        'fa-solid fa-vial'=>'Vial',
        'fa-solid fa-vials'=>'Vials',
        'fa-solid fa-video'=>'Video',
        'fa-solid fa-video-slash'=>'Video Slash',
        'fa-solid fa-vihara'=>'Vihara',
        'fa-solid fa-virus'=>'Virus',
        'fa-solid fa-virus-slash'=>'Virus Slash',
        'fa-solid fa-viruses'=>'Viruses',
        'fa-solid fa-voicemail'=>'Voicemail',
        'fa-solid fa-volleyball'=>'Volleyball',
        'fa-solid fa-volleyball-ball'=>'Volleyball Ball',
        'fa-solid fa-volume-down'=>'Volume Down',
        'fa-solid fa-volume-mute'=>'Volume Mute',
        'fa-solid fa-volume-off'=>'Volume Off',
        'fa-solid fa-volume-up'=>'Volume Up',
        'fa-solid fa-vote-yea'=>'Vote Yea',
        'fa-solid fa-vr-cardboard'=>'Vr Cardboard',
        'fa-solid fa-walking'=>'Walking',
        'fa-solid fa-wallet'=>'Wallet',
        'fa-solid fa-wand-magic-sparkles'=>'Wand Magic Sparkles',
        'fa-solid fa-warehouse'=>'Warehouse',
        'fa-solid fa-water'=>'Water',
        'fa-solid fa-wave-square'=>'Wave Square',
        'fa-solid fa-weight'=>'Weight',
        'fa-solid fa-weight-hanging'=>'Weight Hanging',
        'fa-solid fa-wheelchair'=>'Wheelchair',
        'fa-solid fa-wifi'=>'Wifi',
        'fa-solid fa-wind'=>'Wind',
        'fa-solid fa-window-close'=>'Window Close',
        'fa-solid fa-window-maximize'=>'Window Maximize',
        'fa-solid fa-window-minimize'=>'Window Minimize',
        'fa-solid fa-window-restore'=>'Window Restore',
        'fa-solid fa-wine-bottle'=>'Wine Bottle',
        'fa-solid fa-wine-glass'=>'Wine Glass',
        'fa-solid fa-won-sign'=>'Won Sign',
        'fa-solid fa-wrench'=>'Wrench',
        'fa-solid fa-x-ray'=>'X Ray',
        'fa-solid fa-xmark'=>'Xmark',
        'fa-solid fa-yen-sign'=>'Yen Sign',
        'fa-solid fa-yin-yang'=>'Yin Yang'
    );
}

function ezzy_pr_icon_field($value) {
    $catalog = ezzy_pr_icon_catalog();
    $selected = is_string($value) ? $value : '';
    $selected_label = isset($catalog[$selected]) ? $catalog[$selected] : ($selected ?: 'None');
    $is_fa = strpos($selected, 'fa-') !== false;
    ob_start(); ?>
    <div class="ezzy-pr-fa-picker" data-selected="<?php echo esc_attr($selected); ?>">
        <input type="hidden" class="ezzy-pr-icon-value" name="icon" value="<?php echo esc_attr($selected); ?>">
        <div class="ezzy-pr-fa-current">
            <span class="ezzy-pr-fa-preview"><?php if ($is_fa): ?><i class="<?php echo esc_attr($selected); ?>"></i><?php elseif ($selected): echo esc_html($selected); else: ?><span class="ezzy-pr-fa-none">—</span><?php endif; ?></span>
            <span class="ezzy-pr-fa-current-label"><?php echo esc_html($selected_label); ?></span>
            <button type="button" class="button ezzy-pr-change-icon">Choose Icon</button>
            <button type="button" class="button ezzy-pr-clear-icon">Clear</button>
        </div>
        <div class="ezzy-pr-fa-panel" hidden>
            <input type="search" class="ezzy-pr-fa-search" placeholder="Search icons, e.g. salon, scissors, beauty, car..."><span class="ezzy-pr-fa-count"></span>
            <div class="ezzy-pr-fa-grid">
                <?php foreach ($catalog as $class => $label): ?>
                    <button type="button" class="ezzy-pr-fa-option" data-icon="<?php echo esc_attr($class); ?>" data-label="<?php echo esc_attr($label); ?>">
                        <i class="<?php echo esc_attr($class); ?>"></i>
                        <span><?php echo esc_html($label); ?></span>
                    </button>
                <?php endforeach; ?>
            </div>
        </div>
        <p class="description">Choose a Font Awesome icon. You do not need to type icon class names.</p>
    </div>
    <?php
    return ob_get_clean();
}

function ezzy_pr_platforms() {
    if (!current_user_can('manage_options')) return;
    $items=ezzy_pr_get('ezzy_pr_platforms');
    if (isset($_POST['ezzy_pr_save_platform']) && check_admin_referer('ezzy_pr_platform_save')) {
        $id=sanitize_title($_POST['id'] ?: $_POST['name']);
        $row=array('id'=>$id,'name'=>sanitize_text_field($_POST['name']),'url'=>esc_url_raw($_POST['url']),'partner_url'=>esc_url_raw($_POST['partner_url']),'icon'=>sanitize_text_field($_POST['icon']),'active'=>isset($_POST['active'])?1:0);
        $found=false; foreach($items as &$it){ if($it['id']===$id){$it=$row;$found=true;break;} } unset($it);
        if(!$found) $items[]=$row; update_option('ezzy_pr_platforms',$items); echo '<div class="notice notice-success"><p>Platform saved.</p></div>';
    }
    if (isset($_GET['delete']) && check_admin_referer('ezzy_pr_delete_platform')) {
        $id=sanitize_key($_GET['delete']); $items=array_values(array_filter($items,fn($x)=>$x['id']!==$id)); update_option('ezzy_pr_platforms',$items); echo '<div class="notice notice-success"><p>Platform deleted.</p></div>';
    }
    $edit=null; if(isset($_GET['edit'])) foreach($items as $x) if($x['id']===sanitize_key($_GET['edit'])) $edit=$x;
    echo '<div class="wrap ezzy-pr-admin"><h1>Platforms</h1><p>These are internal EZZY destinations. Vendors only see business categories.</p>';
    echo '<h2>'.($edit?'Edit Platform':'Add Platform').'</h2><form method="post"><table class="form-table"><tr><th>Name</th><td><input class="regular-text" name="name" required value="'.esc_attr($edit['name']??'').'"></td></tr><tr><th>Platform URL</th><td><input class="regular-text" type="url" name="url" value="'.esc_attr($edit['url']??'').'"></td></tr><tr><th>Partner Registration URL</th><td><input class="large-text" type="url" name="partner_url" required value="'.esc_attr($edit['partner_url']??'').'"></td></tr><tr><th>Icon</th><td>'.ezzy_pr_icon_field($edit['icon']??'💼').'</td></tr><tr><th>Status</th><td><label><input type="checkbox" name="active" '.checked(!empty($edit['active']),true,false).'> Active</label></td></tr></table><input type="hidden" name="id" value="'.esc_attr($edit['id']??'').'">'.wp_nonce_field('ezzy_pr_platform_save','_wpnonce',true,false).'<p><button class="button button-primary" name="ezzy_pr_save_platform">Save Platform</button></p></form>';
    echo '<h2>Existing Platforms</h2><table class="widefat striped"><thead><tr><th>Platform</th><th>Partner URL</th><th>Status</th><th></th></tr></thead><tbody>';
    foreach($items as $x){$del=wp_nonce_url(admin_url('admin.php?page=ezzy-pr-platforms&delete='.rawurlencode($x['id'])),'ezzy_pr_delete_platform'); echo '<tr><td>'.esc_html($x['icon'].' '.$x['name']).'</td><td><code>'.esc_html($x['partner_url']).'</code></td><td>'.(!empty($x['active'])?'Active':'Inactive').'</td><td><a href="'.esc_url(admin_url('admin.php?page=ezzy-pr-platforms&edit='.$x['id'])).'">Edit</a> | <a href="'.esc_url($del).'" onclick="return confirm(\'Delete this platform?\')">Delete</a></td></tr>';}
    echo '</tbody></table></div>';
}

function ezzy_pr_categories() {
    if (!current_user_can('manage_options')) return;
    $items=ezzy_pr_get('ezzy_pr_categories'); $platforms=ezzy_pr_get('ezzy_pr_platforms');
    if (isset($_POST['ezzy_pr_save_category']) && check_admin_referer('ezzy_pr_category_save')) {
        $id=sanitize_title($_POST['id'] ?: $_POST['name']);
        $row=array('id'=>$id,'name'=>sanitize_text_field($_POST['name']),'icon'=>sanitize_text_field($_POST['icon']),'platform'=>sanitize_key($_POST['platform']),'url'=>esc_url_raw($_POST['url']),'active'=>isset($_POST['active'])?1:0);
        $found=false; foreach($items as &$it){if($it['id']===$id){$it=$row;$found=true;break;}} unset($it); if(!$found)$items[]=$row; update_option('ezzy_pr_categories',$items); echo '<div class="notice notice-success"><p>Category saved.</p></div>';
    }
    if (isset($_GET['delete']) && check_admin_referer('ezzy_pr_delete_category')) { $id=sanitize_key($_GET['delete']); $items=array_values(array_filter($items,fn($x)=>$x['id']!==$id)); update_option('ezzy_pr_categories',$items); echo '<div class="notice notice-success"><p>Category deleted.</p></div>'; }
    $edit=null; if(isset($_GET['edit'])) foreach($items as $x) if($x['id']===sanitize_key($_GET['edit'])) $edit=$x;
    echo '<div class="wrap ezzy-pr-admin"><h1>Business Categories</h1><p>Users select these categories. The plugin redirects them to the editable URL you set here.</p><h2>'.($edit?'Edit Category':'Add Category').'</h2><form method="post"><table class="form-table"><tr><th>Category Name</th><td><input class="regular-text" name="name" required value="'.esc_attr($edit['name']??'').'"></td></tr><tr><th>Icon</th><td>'.ezzy_pr_icon_field($edit['icon']??'💼').'</td></tr><tr><th>Platform</th><td><select name="platform"><option value="">— None —</option>'; foreach($platforms as $p) echo '<option value="'.esc_attr($p['id']).'" '.selected($edit['platform']??'',$p['id'],false).'>'.esc_html($p['name']).'</option>'; echo '</select></td></tr><tr><th>Destination URL</th><td><input class="large-text" type="url" name="url" required value="'.esc_attr($edit['url']??'').'"><p class="description">This exact URL is opened after the user selects this category.</p></td></tr><tr><th>Status</th><td><label><input type="checkbox" name="active" '.checked(!empty($edit['active']),true,false).'> Active</label></td></tr></table><input type="hidden" name="id" value="'.esc_attr($edit['id']??'').'">'.wp_nonce_field('ezzy_pr_category_save','_wpnonce',true,false).'<p><button class="button button-primary" name="ezzy_pr_save_category">Save Category</button></p></form>';
    echo '<h2>Existing Categories</h2><table class="widefat striped"><thead><tr><th>Category</th><th>Platform</th><th>Destination URL</th><th>Status</th><th></th></tr></thead><tbody>';
    foreach($items as $x){$pname='';foreach($platforms as $p)if($p['id']===$x['platform'])$pname=$p['name'];$del=wp_nonce_url(admin_url('admin.php?page=ezzy-pr-categories&delete='.rawurlencode($x['id'])),'ezzy_pr_delete_category');echo '<tr><td>'.esc_html($x['icon'].' '.$x['name']).'</td><td>'.esc_html($pname).'</td><td><code>'.esc_html($x['url']).'</code></td><td>'.(!empty($x['active'])?'Active':'Inactive').'</td><td><a href="'.esc_url(admin_url('admin.php?page=ezzy-pr-categories&edit='.$x['id'])).'">Edit</a> | <a href="'.esc_url($del).'" onclick="return confirm(\'Delete this category?\')">Delete</a></td></tr>';}
    echo '</tbody></table></div>';
}

function ezzy_pr_settings() {
    if (!current_user_can('manage_options')) return;
    $s=ezzy_pr_get('ezzy_pr_settings');
    if(isset($_POST['ezzy_pr_save_settings']) && check_admin_referer('ezzy_pr_settings_save')){
        $s=array('trigger_class'=>sanitize_html_class($_POST['trigger_class']),'title'=>sanitize_text_field($_POST['title']),'subtitle'=>sanitize_text_field($_POST['subtitle']),'search_placeholder'=>sanitize_text_field($_POST['search_placeholder']),'fallback_text'=>sanitize_text_field($_POST['fallback_text']),'fallback_url'=>esc_url_raw($_POST['fallback_url']));
        update_option('ezzy_pr_settings',$s); echo '<div class="notice notice-success"><p>Settings saved.</p></div>';
    }
    echo '<div class="wrap ezzy-pr-admin"><h1>Settings</h1><form method="post"><table class="form-table"><tr><th>Trigger CSS Class</th><td><input class="regular-text" name="trigger_class" value="'.esc_attr($s['trigger_class']).'"><p class="description">Add this class to your existing Elementor button. Use the class without a leading dot.</p></td></tr><tr><th>Modal Title</th><td><input class="regular-text" name="title" value="'.esc_attr($s['title']).'"></td></tr><tr><th>Subtitle</th><td><input class="large-text" name="subtitle" value="'.esc_attr($s['subtitle']).'"></td></tr><tr><th>Search Placeholder</th><td><input class="regular-text" name="search_placeholder" value="'.esc_attr($s['search_placeholder']).'"></td></tr><tr><th>Fallback Text</th><td><input class="regular-text" name="fallback_text" value="'.esc_attr($s['fallback_text']).'"></td></tr><tr><th>Fallback URL</th><td><input class="large-text" type="url" name="fallback_url" value="'.esc_attr($s['fallback_url']).'"><p class="description">Optional. Leave blank to hide the fallback action.</p></td></tr></table>'.wp_nonce_field('ezzy_pr_settings_save','_wpnonce',true,false).'<p><button class="button button-primary" name="ezzy_pr_save_settings">Save Settings</button></p></form></div>';
}
function ezzy_pr_normalise_referral_code($raw) {
    if (!is_string($raw)) return '';
    $code = strtoupper(preg_replace('/[^A-Za-z0-9]/', '', substr($raw, 0, 256)));
    return preg_match('/^[A-Z0-9]{4,32}$/', $code) ? $code : '';
}

function ezzy_pr_capture_referral_code() {
    if (is_admin() || wp_doing_ajax() || wp_doing_cron()) return;
    if (!isset($_GET[EZZY_PR_REFERRAL_PARAM])) return;
    $code = ezzy_pr_normalise_referral_code(wp_unslash($_GET[EZZY_PR_REFERRAL_PARAM]));
    if ($code === '') return;
    if (!headers_sent()) {
        setcookie(EZZY_PR_REFERRAL_COOKIE, $code, array(
            'expires'  => time() + EZZY_PR_REFERRAL_TTL,
            'path'     => COOKIEPATH ? COOKIEPATH : '/',
            'domain'   => COOKIE_DOMAIN,
            'secure'   => is_ssl(),
            'httponly' => true,
            'samesite' => 'Lax',
        ));
    }
    // setcookie() does not populate $_COOKIE for the current request, and the
    // partner button is most often clicked on the landing page itself.
    $_COOKIE[EZZY_PR_REFERRAL_COOKIE] = $code;
}
add_action('init', 'ezzy_pr_capture_referral_code');

function ezzy_pr_get_referral_code() {
    if (isset($_GET[EZZY_PR_REFERRAL_PARAM])) {
        $code = ezzy_pr_normalise_referral_code(wp_unslash($_GET[EZZY_PR_REFERRAL_PARAM]));
        if ($code !== '') return $code;
    }
    if (isset($_COOKIE[EZZY_PR_REFERRAL_COOKIE])) {
        return ezzy_pr_normalise_referral_code(wp_unslash($_COOKIE[EZZY_PR_REFERRAL_COOKIE]));
    }
    return '';
}

function ezzy_pr_front_assets() {
    $s=ezzy_pr_get('ezzy_pr_settings');
    wp_enqueue_style('ezzy-pr-fontawesome', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css', array(), '6.7.2');
    wp_enqueue_style('ezzy-pr-front',EZZY_PR_URL.'assets/frontend.css',array('ezzy-pr-fontawesome'),EZZY_PR_VERSION);
    wp_enqueue_script('ezzy-pr-front',EZZY_PR_URL.'assets/frontend.js',array(),EZZY_PR_VERSION,true);
    $ref=ezzy_pr_get_referral_code();
    $categories=array_values(array_filter(ezzy_pr_get('ezzy_pr_categories'),fn($x)=>!empty($x['active'])));
    $fallback_url=$s['fallback_url'] ?? '';
    if ($ref!=='') {
        foreach ($categories as &$cat) { if (!empty($cat['url'])) $cat['url']=add_query_arg(EZZY_PR_REFERRAL_OUT_PARAM,$ref,$cat['url']); }
        unset($cat);
        if ($fallback_url!=='') $fallback_url=add_query_arg(EZZY_PR_REFERRAL_OUT_PARAM,$ref,$fallback_url);
    }
    wp_localize_script('ezzy-pr-front','EZZYPartnerRouting',array(
        'triggerClass'=>'.'.sanitize_html_class($s['trigger_class']),
        'title'=>$s['title'],'subtitle'=>$s['subtitle'],'searchPlaceholder'=>$s['search_placeholder'],
        'fallbackText'=>$s['fallback_text'],'fallbackUrl'=>$fallback_url,
        'categories'=>$categories,
        'closeLabel'=>'Close'
    ));
}
add_action('wp_enqueue_scripts','ezzy_pr_front_assets');
