// Standalone fixture controller, NOT an application component or payment state machine.
// All numbers/outcomes are fixed mock snapshots. No storage, network, provider or auth.
const icons = {
  qr: '<rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="3" width="6" height="6" rx="1"/><rect x="3" y="15" width="6" height="6" rx="1"/><path d="M15 15h3v3h3v3h-6v-3h-3v-3h3Z"/>',
  phone: '<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 18h4M10 5h4"/>',
  check: '<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  warning: '<path d="M10 4 2 18a2 2 0 0 0 2 3h16a2 2 0 0 0 2-3L14 4a2 2 0 0 0-4 0Z"/><path d="M12 9v4M12 17h.01"/>',
  offline: '<path d="m2 2 20 20M8.5 16.5a5 5 0 0 1 7 0M12 20h.01M5 12a10 10 0 0 1 5-2M14 10a10 10 0 0 1 5 2M2 7a16 16 0 0 1 3-2M9 3a16 16 0 0 1 13 4"/>',
  lock: '<rect x="4" y="10" width="16" height="12" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 15v3"/>',
};
const icon = (name) => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]}</svg>`;
const button = (label, target, primary = false) => `<button type="button" class="button${primary ? ' primary' : ''}" data-screen="${target}">${label}</button>`;
const summary = (free = false) => `<aside class="card"><p class="eyebrow">Your booking</p><h2 class="service">Studio session</h2><dl class="details"><div class="detail"><dt>When</dt><dd>Thu, 8 Oct 2026<br>2:00–3:00 PM · Manila</dd></div><div class="detail"><dt>Duration</dt><dd>1 × 1 hour</dd></div></dl><div class="total"><span>${free ? 'Total' : 'Amount to pay'}</span><strong>${free ? 'Free' : '₱500'}</strong></div><p class="note">Sample booking only. No real customer details are used in these previews.</p></aside>`;
const timer = () => '<div class="timer"><span>Time left to complete payment</span><strong>04:32</strong></div>';
const spinner = () => '<span class="spinner" aria-hidden="true"></span>';
const header = (title, sub, back = false) => `<div class="flow-head">${back ? '<button type="button" class="back" data-screen="choice" aria-label="Back to review preview">←</button>' : ''}<div class="headings"><h1>${title}</h1><p class="sub">${sub}</p></div><span class="pill step">Payment</span></div>`;
const footer = (copy, controls = '') => `<div class="actions"><p class="actions-copy">${copy}</p><div class="button-group">${controls}</div></div>`;
const split = (panel) => `<div class="content"><div class="layout">${summary()}<section class="card">${panel}</section></div></div>`;
const center = (symbol, title, copy, panel, controls, tone = '', extra = '') => `<div class="content"><section class="card center-wrap"><div class="status-icon ${tone}">${icon(symbol)}</div><h2 class="state-heading">${title}</h2><p class="state-copy">${copy}</p>${panel ? `<div class="status-panel">${panel}</div>` : ''}${extra}${controls ? `<div class="button-group">${controls}</div>` : ''}</section></div>`;

const screens = {
  choice: () => header('Review & pay', 'Check your booking, then choose how to pay.', true) + split(`<h2 class="payment-title">Choose your payment method</h2><p class="sub">Only your selected method will be prepared.</p><div class="methods"><button type="button" class="method recommended" data-screen="qr"><span class="icon-box">${icon('qr')}</span><span><span class="method-label">Pay with QR Ph <span class="badge">Recommended</span></span><span class="method-desc">Scan using GCash or another QR Ph app<br>on your own phone.</span></span><span class="chevron" aria-hidden="true">›</span></button><button type="button" class="method" data-screen="gcash"><span class="icon-box">${icon('phone')}</span><span><span class="method-label">Pay with GCash</span><span class="method-desc">Continue to GCash on this device.<br>Returning here won't start another payment.</span></span><span class="chevron" aria-hidden="true">›</span></button></div><p class="note">Once your payment is ready, you have 5 minutes to complete it. Reloading or retrying won't extend that time.</p>`) + footer('Your booking is not paid yet. Choosing a method starts preparation; this preview only changes screens.', button('Next customer', 'reset')),
  preparing: () => header('Preparing your payment', 'Keep this screen open.') + center('clock', 'Getting payment ready', 'We’re preparing your selected method. Please don’t start another payment.', `${spinner()} Same booking · same payment attempt<br>No five-minute payment countdown until the payment action is ready.`, '') + footer('Preparation has its own two-minute limit. This is a fixed loading preview.', button('Next customer', 'reset')),
  qr: () => header('Pay with QR Ph', 'Use your own phone to scan and pay.') + split(`${timer()}<div class="qr-view"><h2 class="payment-title">Scan to pay ₱500</h2><div class="qr-frame" role="img" aria-label="Preview QR placeholder. Not scannable.">${icon('qr')}<span class="demo-qr">PREVIEW ONLY</span></div><p class="instruction">Open GCash or another QR Ph app on your phone.<br>Scan the code and check the amount before paying.</p><p class="waiting">${spinner()} Waiting for verified payment</p><button type="button" class="text-button" data-screen="checking">Check payment status</button><p class="note">QR placeholder · not scannable.<br>Production uses PayMongo’s returned QR image. No QR package needed.</p></div>`) + footer('No “renew QR” button. Checking status does not create a new payment or extend the hold.', button('Cancel booking', 'expired') + button('Next customer', 'reset')),
  gcash: () => header('Pay with GCash', 'Continue securely, then return to this booking.') + split(`${timer()}<div class="qr-view"><div class="status-icon">${icon('phone')}</div><h2 class="payment-title">Continue to GCash</h2><p class="state-copy">GCash will open on this device to complete your ₱500 payment.</p><div class="button-group"><button type="button" class="button primary" data-screen="checking">Continue to GCash ↗</button></div><p class="note">Already opened GCash? Returning here checks the same payment—it does not create another charge.</p><p class="note">Before leaving this shared device, make sure your GCash session is closed. QR Ph lets you pay on your own phone instead.</p></div>`) + footer('GCash’s page is external and is not redesigned here. The preview button opens a mock return screen only.', button('Cancel booking', 'expired') + button('Next customer', 'reset')),
  checking: () => header('Checking your payment', 'A return from GCash is not proof of payment.') + center('clock', 'Waiting for payment confirmation', 'We haven’t verified a completed payment yet. If you already paid, don’t pay again.', `${spinner()} Checking the original payment<br>Mock remaining time: 04:32 · the deadline has not changed.`, button('Check again', 'checking', true)) + footer('Cancel and Next customer are not the same: Next customer ends visibility without extending or cancelling the original hold.', button('Cancel booking', 'expired') + button('Next customer', 'reset')),
  received: () => header('Payment received', 'Your payment has been verified.') + center('check', 'Payment received', 'Your booking has been submitted and is awaiting vendor confirmation.', '<strong>₱500 received</strong><br>Studio session · Thu, 8 Oct · 2:00–3:00 PM<br>Manila time · Awaiting vendor confirmation', button('Done — next customer', 'reset', true), 'success', '<p class="reference">Booking reference <strong>DEMO-7K2P</strong></p><p class="note">Mock verified receipt. “Booking confirmed” is reserved for a verified vendor-confirmed booking.</p>') + footer('Take note of your reference before continuing. Next customer hides this receipt.'),
  expired: () => header('Payment window ended', 'This example shows a server-verified release.') + center('clock', 'This booking was released', 'The payment window ended and this booking is no longer reserved. A new booking depends on current availability.', 'If you already paid, don’t pay again. Ask the front desk to contact Ezzy operations to investigate.<br>Payment checks can continue after release.', button('Start a new booking', 'choice', true), '', '<p class="note">Preview shortcut only. Production must start a fresh availability/booking flow, never reuse this booking.</p>') + footer('A local timer reaching zero alone must not claim server-confirmed release.'),
  late: () => header('Payment needs attention', 'Payment received after the booking was released.') + center('warning', 'Payment received · booking not confirmed', 'We received your payment, but the booking was already released. Please ask the front desk for help.', 'Ezzy operations will investigate and arrange the next steps.<br>No automatic rebooking or guaranteed immediate refund.', button('Done — next customer', 'reset', true), 'alert', '<p class="reference">Booking reference <strong>DEMO-7K2P</strong></p>') + footer('Verified exception snapshot—not a standard successful booking receipt.'),
  offline: () => header('Connection lost', 'Your payment status is currently unknown.') + center('offline', 'We can’t check your payment right now', 'If you already paid, don’t pay again. Reconnect to check the same payment, or ask the front desk for help.', 'The original payment deadline still applies.<br>No new payment or QR is generated by retrying.', button('Try connection again', 'checking', true)) + footer('These preview controls simulate outcomes, not connectivity.', button('Next customer', 'reset')),
  reset: () => header('Getting the kiosk ready', 'Customer details are hidden.') + center('lock', 'Please wait for the front desk', 'We’re waiting for the server to confirm that the previous interaction is closed. The next customer cannot start yet.', 'This does not cancel or refund a payment.<br>Staff can retry recovery without waiting for PayMongo.<br>No offline bypass is available.', button('Staff recovery', 'recovery', true)) + footer('Privacy-safe screen: no name, booking details, QR, amount or previous customer reference.'),
  inuse: () => header('Kiosk already in use', 'Please use the original booking tab.') + center('lock', 'A booking is open in another tab', 'This tab cannot display or take over that customer’s booking. Ask the front desk if the original tab is unavailable.', 'No customer details are shown here.<br>Staff recovery requires deliberate confirmation.', button('Staff recovery', 'recovery')) + footer('Presentation only. Tab-ownership enforcement remains parked and must be proven before rollout.'),
  recovery: () => header('Staff recovery', 'For the currently signed-in vendor administrator only.') + center('lock', 'Reset this kiosk interaction?', 'This closes the current customer interaction. It does not cancel the booking, refund a payment or extend its deadline.', '', button('Keep kiosk blocked', 'reset') + '<button type="button" class="button primary" disabled>Verify & reset — preview only</button>', '', '<div class="recovery-placeholder"><strong>Administrator password field goes here.</strong><br>Intentionally not interactive: do not enter real credentials into a design preview. Production requires fresh server-verified authentication and confirmed invalidation.</div>') + footer('No password collection, sign-in, server reset or offline override exists in this preview.'),
  free: () => header('No payment needed', 'This example shows a verified free booking.') + center('check', 'Booking submitted', 'There’s nothing to pay. Your booking is awaiting vendor confirmation.', '<strong>Total: Free</strong><br>No QR or GCash attempt is created.', button('Done — next customer', 'reset', true), 'success') + footer('Mock free result only. Pricing and success come from the server in production.'),
};

const screenControl = document.getElementById('screen');
const themeControl = document.getElementById('theme');
const preview = document.getElementById('preview');
const params = new URLSearchParams(window.location.search);
function render(screen) {
  const selected = Object.hasOwn(screens, screen) ? screen : 'choice';
  screenControl.value = selected;
  // All templates above are author-controlled constants; never accept API/user HTML.
  preview.innerHTML = screens[selected]();
}
function setTheme(theme) {
  const dark = theme === 'dark';
  document.documentElement.classList.toggle('dark', dark);
  themeControl.value = dark ? 'dark' : 'light';
}
screenControl.addEventListener('change', () => render(screenControl.value));
themeControl.addEventListener('change', () => setTheme(themeControl.value));
document.addEventListener('click', (event) => {
  const target = event.target instanceof Element ? event.target.closest('[data-screen]') : null;
  if (target instanceof HTMLButtonElement) render(target.dataset.screen);
});
render(params.get('screen'));
setTheme(params.get('theme'));
