#!/usr/bin/env python3
"""Generate .plans/INDEX.md from each plan's header lines.

INDEX.md is generated — never hand-edit it. Re-run this after creating or
closing a plan:

    python3 scripts/plans-index.py          # rewrite .plans/INDEX.md
    python3 scripts/plans-index.py --check  # exit 1 if INDEX.md is stale

Reads, per plan: the first H1, the date (from the filename), the scope line
(`**App / scope:**` and its older variants), the `**Status:**` line, and any
predecessor / supersession reference. Plans whose status says `legacy` are
listed in a separate trailing section. Standard library only.
"""
import re
import sys
from pathlib import Path

PLANS = Path(__file__).resolve().parent.parent / ".plans"
INDEX = PLANS / "INDEX.md"

STATUS_RE = re.compile(r"^Status:\s*(?:[✅🔄✖⏸⬜]️?\s*)?(DRAFT|IN PROGRESS|COMPLETE|BLOCKED|ABORTED)\b[\s—–:.-]*(.*)")
SCOPE_RE = re.compile(r"^\*{0,2}(?:App / scope|Scope|Target|Applies to|Page)\*{0,2}:\*{0,2}\s*(.*)")
RELATED_RE = re.compile(r"(Predecessor|Supersedes|superseded by|Successor)\b[^`\n]*`\.plans/([^`]+?)\.md`", re.I)


def clean(text, limit):
    text = re.sub(r"[*`]", "", text).replace("|", "/").strip()
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def parse(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    head = lines[:40]
    title = next((re.sub(r"^(> )?# ", "", l) for l in lines if re.match(r"^(> )?# ", l)), path.stem)
    status, note = "—", ""
    for l in head:
        m = STATUS_RE.match(l.replace("*", ""))
        if m:
            status, note = m.group(1), m.group(2)
            break
    scope = next((m.group(1) for l in head if (m := SCOPE_RE.match(l))), "")
    related = sorted({f"{k.lower()} {v[:10]}" for k, v in RELATED_RE.findall("\n".join(head))})
    return {
        "file": path.name,
        "date": path.name[:10],
        "title": clean(title, 80),
        "status": status,
        "note": clean(note, 110),
        "scope": clean(scope, 70),
        "related": "; ".join(related),
        "legacy": "legacy" in note.lower(),
    }


def table(rows):
    out = ["| Date | Plan | Status | Scope | Related |", "|---|---|---|---|---|"]
    for r in rows:
        sep = " " if r["note"].startswith("(") else " — "
        status = r["status"] + (sep + r["note"] if r["note"] else "")
        out.append(f"| {r['date']} | [{r['title']}]({r['file']}) | {status} | {r['scope']} | {r['related']} |")
    return out


def render():
    rows = sorted((parse(p) for p in PLANS.glob("2*.md")), key=lambda r: r["file"], reverse=True)
    current = [r for r in rows if not r["legacy"]]
    legacy = [r for r in rows if r["legacy"]]
    counts = {}
    for r in current:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    summary = " · ".join(f"{k} {v}" for k, v in sorted(counts.items()))
    out = [
        "# Plans index",
        "",
        "<!-- GENERATED by scripts/plans-index.py — do not edit by hand; re-run the script. -->",
        "",
        f"{len(rows)} plans — current: {summary} · legacy: {len(legacy)}.",
        "Status and scope come from each plan's own header; open the plan before relying on it.",
        "",
        "## Current",
        "",
        *table(current),
        "",
        "## Legacy (pre-pivot DriveBook — apps no longer in the workspace)",
        "",
        *table(legacy),
        "",
    ]
    return "\n".join(out)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        if not INDEX.exists() or INDEX.read_text(encoding="utf-8") != text:
            print("INDEX.md is stale — run: python3 scripts/plans-index.py", file=sys.stderr)
            return 1
        return 0
    INDEX.write_text(text, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(PLANS.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
